# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: 빌드 시작
    runs-on: ubuntu-latest
    steps:
      - name: 소스코드 가져오기
        uses: actions/checkout@v2

      - name: 보안파일 master.key 생성
        id: create-masterkey
        run: |
          echo "${{ secrets.RAILS_MASTER_KEY }}" > ./config/master.key
          echo $(pwd)
          ls -la ./config/master.key

      - name: 배포용 패키지 제작
        run: zip deploy.zip -9 -r --exclude='*.git*' --exclude='*.DS_Store*' --exclude='test/*' --exclude='node_modules/*' --exclude='tmp/*' ./
      
      - name: 배포용 패키지 확인
        run: ls -lah deploy.zip


      - name: 빌드 번호 생성
        id: buildnumber
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}
        
      - name: 버전관리용 태그 가져오기
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: 배포 시작
        uses: einaregilsson/beanstalk-deploy@v9
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: C0r0N4r4n99e
          environment_name: C0r0n4r4n99e-env
          version_label: ${{ steps.buildnumber.outputs.build_number }}
          region: ap-northeast-2
          deployment_package: deploy.zip
          wait_for_deployment: false
